// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bff

import (
	"github.com/DaHuangQwQ/gpkg/logger"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitBff(l logger.Logger, redisClient redis.Cmdable) *App {
	v := initServer()
	server := initGinServer(redisClient, l, v...)
	app := &App{
		Server: server,
	}
	return app
}
