// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bff

import (
	"github.com/DaHuangQwQ/gpkg/logger"
	"github.com/DaHuangQwQ/web/internal/bff/web"
	"github.com/DaHuangQwQ/web/internal/user"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitApp(l logger.Logger, redisClient redis.Cmdable, userService *user.App) *App {
	userHandler := web.NewUserHandler(userService)
	server := initGinServer(redisClient, l, userHandler)
	app := &App{
		Server: server,
	}
	return app
}
