// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/DaHuangQwQ/web/internal/bff"
	"github.com/DaHuangQwQ/web/internal/user"
	"github.com/DaHuangQwQ/web/ioc/third"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := third.InitLogger()
	cmdable := third.InitRedis()
	app := user.InitApp()
	bffApp := bff.InitApp(logger, cmdable, app)
	server := bffApp.Server
	iocApp := &App{
		Server: server,
	}
	return iocApp
}

// wire.go:

var thirdSet = wire.NewSet(third.InitLogger, third.InitRedis)
