// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"main/internal/bff"
	"main/ioc/third"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := third.InitLogger()
	cmdable := third.InitRedis()
	app := bff.InitBff(logger, cmdable)
	server := app.Server
	iocApp := &App{
		Server: server,
	}
	return iocApp
}

// wire.go:

var thirdSet = wire.NewSet(third.InitLogger, third.InitRedis)
